sudo: required
language: node_js
node_js:
    - "node"
cache:
    directories:
        - "node_modules"
before_install:
    - npm install -g node-gyp
env:
    - CXX=g++-5
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
